### PR TITLE
Fix macros binded on rotatory encoder

### PR DESCRIPTION
**Pull request by yhemery**
Fixes issue #19

### CODE REVIEW

**Comment by rickyphewitt** [comment]
Would be great to get this change in. Spent a few minutes trying to figure out why my right knob was doing the exact opposite of what I wanted :).

**Comment by rickyphewitt** [comment]
Also FWIW I cherry picked @yhemery 's fix and applied it to my fork in this branch: https://github.com/rickyphewitt/DeepDeck.Ahuyama.fw/tree/rotaryFixTest

and flashed my DeepDeck. Right volume knob now works correctly. :smile: 

Semi Related: 
My test branch is 1 commit before this one: https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/commit/f5810e87d4df2c231674ba780afa90eb834a6ad2

If I try to build and flash latest Main I get an error: 
```
/home/ricky/dev/DeepDeck.Ahuyama.fw/build/../components/bus/i2c_bus.c:391: undefined reference to `i2s_user_unlock'
/home/ricky/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/oled/liboled.a(u8g2_esp32_hal.c.obj):(.literal.u8g2_esp32_i2c_byte_cb+0x38): undefined reference to `i2s_user_lock'
/home/ricky/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/oled/liboled.a(u8g2_esp32_hal.c.obj):(.literal.u8g2_esp32_i2c_byte_cb+0x3c): undefined reference to `i2s_user_unlock'
/home/ricky/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/oled/liboled.a(u8g2_esp32_hal.c.obj): in function `u8g2_esp32_i2c_byte_cb':
/home/ricky/dev/DeepDeck.Ahuyama.fw/build/../components/oled/u8g2_esp32_hal.c:166: undefined reference to `i2s_user_lock'
/home/ricky/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/ricky/dev/DeepDeck.Ahuyama.fw/build/../components/oled/u8g2_esp32_hal.c:167: undefined reference to `i2s_user_unlock'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

 *  The terminal process "/usr/bin/bash '-c', 'ninja '" terminated with exit code: 1. 
```

I know the tip of main is a WIP so its not a big deal, but if anyone is curious why I'm a commit behind main in my testing this is it.

**Comment by fbettag** [comment]
Can someone please review and merge this?

**Comment by rickyphewitt** [comment]
Based on the Repo's contributing agreement all pull requests should be made against the `develop` branch and not main. 

https://github.com/DeepSea-Developments/DeepDeck.Ahuyama.fw/blob/main/CONTRIBUTING.md#understanding-the-repository-structure

@yhemery ,

I know its been awhile do you mind creating a pull request for this fix against the `develop` branch?

**Comment by yhemery** [comment]
Looks like trying to merge on `develop`  is generating a conflict, I'll have a look when possible.

**Comment by JesusVC94** [comment]
Please review the version 0.6.1,  now it should work

**Pull request closed without merging**
